version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg > gpg.txt
      - apt-key add gpg.txt
      - apt-get -y update
      - apk --update add curl
      - apk --update add py-pip
      - apk --update add jq
      - pip install --upgrade awscli
      - workdir=/tmp/delivery_req
      - curl -qL -o aws_credentials.json 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
      
  build:
    commands:
      - source_root_dir=`pwd`
      - cp -R ./step_functions workdir
      # deploy serverless
      - npm config set save-exact true
      - npm install
      - npm install -g serverless
      - npm list --depth=0 | grep step-functions
      - sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - sls deploy
      - python3 -m pip install -r requirements.txt
