version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - workdir=/tmp/delivery_req
  build:
    commands:
      - source_root_dir=`pwd`
      - cp -R ./step_functions workdir
      # deploy serverless
      - npm config set save-exact true
      - npm install
      - npm install -g serverless
      - npm list --depth=0 | grep step-functions
      - sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - sls deploy
      - python3 -m pip install -r requirements.txt
